// constants.js

export const sampleProducts = [
    {
      id: "1",
      name: "V91C",
      category: "Push and pull Lock",
      subcategory: "Single system",
      description: "BODINI Single system fully automatic smart lock",
      features: ["Fingerprint Recognition", "Mobile App Control", "Auto-locking Function"],
      imageUrl:
        "/v26c.jpg",
      isNew: true,
      isHot: false,
      system: "single",
      tags: ["New Product", "Single system"],
    },
    {
      id: "2",
      name: "C90",
      category: "Push and pull Lock",
      subcategory: "Double system",
      description: "BODINI Double system fully automatic smart lock",
      features: ["RFID Card Access", "PIN Code Entry", "Weather Resistant"],
      imageUrl:
        "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
      isNew: false,
      isHot: false,
      system: "double",
      tags: ["Double system"],
    },
    {
      id: "3",
      name: "V61C",
      category: "Push and pull Lock",
      subcategory: "Double system",
      description: "BODINI Double system fully automatic smart lock",
      features: [
        "Touch Screen Interface",
        "Bluetooth Connectivity",
        "Emergency Key Override",
      ],
      imageUrl:
        "https://pixabay.com/get/gc6ad001accb2bc59903a0c7afffe0f3513920cc0af499fddde36c2c4047d3ebfc9d8cfba470aa4e24d2c127b3cc199ced91e7f82bad45752602a9b4a73e2a1bc_1280.jpg",
      isNew: false,
      isHot: false,
      system: "double",
      tags: ["Double system"],
    },
    {
      id: "4",
      name: "c90",
      category: "Push and pull Lock",
      subcategory: "Double system",
      description: "BODINI Double system fully automatic smart lock",
      features: ["Multi-factor Authentication", "Remote Monitoring", "Anti-tampering Alarm"],
      imageUrl:
        "/c90.jpg",
      isNew: false,
      isHot: true,
      system: "double",
      tags: ["Hot", "Double system"],
    },
    {
      id: "5",
      name: "I9909",
      category: "Push and pull Lock",
      subcategory: "Double system",
      description: "BODINI Double system fully automatic smart lock",
      features: ["Facial Recognition", "Voice Control", "Cloud Integration"],
      imageUrl:
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
      isNew: false,
      isHot: false,
      system: "double",
      tags: ["Double system"],
    },
    {
      id: "6",
      name: "I9995",
      category: "Push and pull Lock",
      subcategory: "Double system",
      description: "BODINI Double system fully automatic smart lock",
      features: ["NFC Access", "Backup Battery", "Tamper Detection"],
      imageUrl:
        "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
      isNew: false,
      isHot: false,
      system: "double",
      tags: ["Double system"],
    },
    {
      id: "7",
      name: "V81C",
      category: "Push and pull Lock",
      subcategory: "Single system",
      description: "BODINI Single system fully automatic smart lock",
      features: ["Palm Recognition", "App Notifications", "Energy Efficient"],
      imageUrl:
        "/v81c.jpg",
      isNew: true,
      isHot: true,
      system: "single",
      tags: ["New Product", "Hot", "Single system"],
    },
    {
      id: "8",
      name: "A2",
      category: "Commercial digital locks",
      subcategory: "Slim door/window lock",
      description: "A2 Waterproof Tuya wifi/ Tuya zigbee /TTlock ble APP Broken Bridge Aluminium Smart Lock",
      features: ["Slim Design (8mm)", "Fingerprint Recognition", "Bluetooth Connectivity", "Glass Door Compatible"],
      imageUrl: "/A2.jpg",
      isNew: true,
      isHot: false,
      system: "slim",
      tags: ["New Product", "Slim Design"],
    },
    {
      id: "9",
      name: "A3",
      category: "Commercial digital locks",
      subcategory: "Slim door/window lock",
      description: "A3 Smart tuya wifi /TTLock Ble app face recognition aluminum door lock",
      features: ["Ultra-thin Profile", "NFC Access", "Auto-lock Function", "Weather Resistant"],
      imageUrl: "/A3.png",
      isNew: false,
      isHot: true,
      system: "slim",
      tags: ["Hot", "Premium", "Slim Design"],
    },
    {
      id: "10",
      name: "DQ",
      category: "Commercial digital locks",
      subcategory: "Slim door/window lock",
      description: "DQ Waterproof TTLock Ble APP Smart Fingerprint Broken Bridge Aluminium Sliding Door Lock",
      features: ["Compact Size", "PIN Code Entry", "Emergency Key Override", "Easy Installation"],
      imageUrl: "/DQ.jpg",
      isNew: false,
      isHot: false,
      system: "slim",
      tags: ["Compact", "Residential"],
    },
    {
        id: "9",
        name: "JO3",
        category: "Commercial digital locks",
        subcategory: "Slim door/window lock",
        description:"J03 Ultra-narrow Smart tuya wifi APP 3D face recognition lock",
        features: ["Ultra-thin Profile", "NFC Access", "Auto-lock Function", "Weather Resistant"],
        imageUrl: "/JO3.jpg",
        isNew: false,
        isHot: true,
        system: "slim",
        tags: ["Hot", "Premium", "Slim Design"],
      },
      {
        id: "9",
        name: "TC6",
        category: "Commercial digital locks",
        subcategory: "Slim door/window lock",
        description: "T6C Waterproof Tuya wifi APP smart face recognition door lock with camera",
        features: ["Ultra-thin Profile", "NFC Access", "Auto-lock Function", "Weather Resistant"],
        imageUrl: "/TC6.jpg",
        isNew: false,
        isHot: true,
        system: "slim",
        tags: ["Hot", "Premium", "Slim Design"],
      },
      {
        id: "9",
        name: "TP007",
        category: "Commercial digital locks",
        subcategory: "Slim door/window lock",
        description: "TP007 Smart Tuya wifi APP aluminum sliding fingerprint door lock",
        features: ["Ultra-thin Profile", "NFC Access", "Auto-lock Function", "Weather Resistant"],
        imageUrl: "/TP007.jpg",
        isNew: false,
        isHot: true,
        system: "slim",
        tags: ["Hot", "Premium", "Slim Design"],
      },
      {
        id: "9",
        name: "YO2",
        category: "Commercial digital locks",
        subcategory: "Slim door/window lock",
        description: "Y02 Waterproof Tuya wifi/ Tuya zigbee /TTlock ble APP Broken Bridge Aluminium Smart Lock",
        features: ["Ultra-thin Profile", "NFC Access", "Auto-lock Function", "Weather Resistant"],
        imageUrl: "/YO2.jpg",
        isNew: false,
        isHot: true,
        system: "slim",
        tags: ["Hot", "Premium", "Slim Design"],
      },
  ];
  