export const sampleProducts = [
  {
    id: "1",
    name: "F7 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F7/F7.jpg",
    images: ["/F7/F71.png", "/F7/F72.jpg", "/F7/F73.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      " A professional electronic lock for hotels featuring 304 stainless steel construction, Euro/ANSI mortise compatibility, mechanical emergency override, and certified security (EN14846/EN1634). Operates on AA batteries with extreme temperature resilience (-40°C to 80°C)..",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions_front: "285.7mm x 78mm",
      product_dimensions_rear: "303.5mm x 78mm",
      mortise_compatibility: "Euro Mortise, ANSI Mortise",
      color: "Silver, Black, Gold",
      battery: "4 x 1.5V AA alkaline batteries",
      battery_installation_location: "Inside of the rear body",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storable_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_temperature: "-20°C to 66°C",
      certificate: "Certified to EN14846:2008 and EN1634-1:2014/A:2018",
    },
  },
  {
    id: "2",
    name: "F1 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F1/F1.jpg",
    images: ["/F1/F11.jpg", "/F1/F12.jpg", "/F1/F13.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "F1 Hotel Lock - A professional-grade electronic hotel lock crafted from durable 304 stainless steel. Features Euro/ANSI mortise compatibility, mechanical emergency override, and reliable 4xAA battery operation. Certified for security (EN14846, EN1634) and built to withstand extreme temperatures from -40°C to 80°C. Available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions_front: "284.25mm x 78mm",
      product_dimensions_rear: "303.5mm x 78mm",
      applicable_lock_body: "Euro Mortise, ANSI Mortise",
      color: "Silver, Black, Gold",
      battery: "4 x 1.5V Alkaline Battery",
      battery_installation_location: "Inside of the rear body",
      emergency_door_opening_method:
        "Euro profile emergency opening by mechanical override",
      storage_ambient_temperature:
        "-40 °C to 80 °C, Non-condensing Environment",
      operating_test_ambient_temperature: "-20 °C to 66 °C",
      certificate: "Certified to EN14846:2008 and EN1634-1:2014/A:2018",
    },
  },

  {
    id: "3",
    name: "P7 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/P7/P7.png",
    images: ["/P7/P71.png", "/P7/P72.png", "/P7/P73.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "P7 Lock - A robust electronic lock featuring durable 304 stainless steel construction with compact handle design (60x148.9mm). Compatible with both Euro and ANSI mortise systems, it operates on 4 AA batteries housed internally. Includes mechanical emergency override and withstands extreme temperatures from -40°C to 80°C. Available in silver and black finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions:
        "Front Handle: 60mm x 148.9mm, Rear Handle: 60mm x 148.9mm",
      mortise_compatibility: "Euro Mortise, ANSI Mortise",
      metal_finishes: "Silver, Black",
      power: "4 x 1.5V Alkaline Batteries",
      battery_location: "Inside the mortise module",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storage_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "4",
    name: "P5 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/P5/P5.jpg",
    images: ["/P5/P51.png", "/P5/P52.png", "/P5/P53.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "P5 Lock - A durable electronic lock crafted from 304 stainless steel, featuring a sleek design with front (284.3x78mm) and rear (303.5x78mm) panels. Compatible with Euro and ANSI mortise systems, it operates on 4 AA batteries and includes mechanical key emergency access. Certified to EN14846 and EN1634 standards, it performs reliably in extreme temperatures from -40°C to 80°C. Available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions_front: "284.3mm x 78mm",
      product_dimensions_rear: "303.5mm x 78mm",
      mortise_compatibility: "Euro Mortise, ANSI Mortise",
      metal_finishes: "Silver, Black, Gold",
      power: "4 x 1.5V Alkaline Batteries",
      battery_location: "Inside of the rear body",
      emergency_opening_method:
        "Emergency Unlocking with Mechanical Key Available",
      storage_temperature: "-40°C to 80°C, Non-condensing Environment",
      operating_test_temperature: "-20°C to 66°C",
      certificate: "Certified to EN14846:2008 and EN1634-1:2014/A:2018",
    },
  },

  {
    id: "5",
    name: "P3 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/P3/P3.png",
    images: ["/P3/P31.png", "/P3/P32.jpg", "/P3/P33.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "P3 Lock- A sleek electronic lock with aluminum alloy handles, compact 60x145mm design. Compatible with Euro/ANSI mortise systems, powered by 4 AA batteries. Features mechanical emergency override, operates in extreme temperatures (-40°C to 80°C), and carries EN14846/EN1634 certifications. Available in black and satin nickel finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "60mm x 145mm",
      mortise_compatibility: "Euro Mortise, ANSI Mortise",
      metal_finishes: "Black, Satin Nickel",
      power: "4 x 1.5V Alkaline Batteries",
      battery_location: "Inside of the mortise module",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storage_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate: "Certified to EN14846:2008 and EN1634-1:2014/A:2018",
    },
  },

  {
    id: "6",
    name: "K8 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/K8H/K8.png",
    images: ["/K8H/K81.jpg", "/K8H/K82.png", "/K8H/K83.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "K8 Lock - A robust aluminum alloy electronic lock featuring a streamlined design (318x78-81.5mm). Offers versatile compatibility with Euro, ANSI, and multiple mortise types (5572/6085/6068). Powered by 4 AA batteries with mechanical emergency override. Built to withstand extreme temperatures from -40°C to 80°C. Available in sophisticated black and coffee gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions_front: "318 mm x 78 mm",
      product_dimensions_rear: "318 mm x 81.5 mm",
      mortise_compatibility:
        "Euro Mortise, ANSI Mortise, 5572, 6085, 6068 Mortise",
      metal_finishes: "Black, Coffee Gold",
      power: "4 pcs x 1.5V Alkaline Batteries",
      battery_location: "Inside of the rear body",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storable_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "7",
    name: "H2 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/H2/H2.png",
    images: ["/H2/H21.png", "/H2/H22.png", "/H2/H23.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "H2 Lock - A slim 304 stainless steel electronic lock with compact 303.4x41.4mm profile. Features extensive mortise compatibility (Euro, ANSI, and 5 additional types). Powered by 4 AA batteries with mechanical emergency override. Withstands extreme temperatures (-40°C to 80°C) and complies with RED & RoHS standards. Available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions: "303.4mm x 41.4mm",
      mortise_compatibility:
        "Euro Mortise, ANSI Mortise, 2885, 3585, 4585, 5572, 6085 Mortise",
      metal_finishes: "Silver, Black, Gold",
      power: "4 x 1.5V Alkaline Batteries",
      battery_location: "Inside of the rear body",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storage_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate:
        "Complies with Radio Equipment Directive (RED) 2014/53/EU and RoHS standards",
    },
  },

  {
    id: "8",
    name: "H1 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/H1/H1.png",
    images: ["/H1/H11.png", "/H1/H12.png", "/H1/H13.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "H1 Lock- A premium 304 stainless steel electronic lock with a slim profile (303.4×41.4mm). Supports a wide range of mortise types including Euro, ANSI, 2885, 3585, 4585, 5572, and 6085. Powered by 4 AA batteries and includes mechanical emergency override. Certified to RED and RoHS standards, it performs reliably in extreme temperatures from -40°C to 80°C. Available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions: "303.4mm x 41.4mm",
      mortise_compatibility: [
        "Euro Mortise",
        "ANSI Mortise",
        "2885",
        "3585",
        "4585",
        "5572",
        "6085",
      ],
      metal_finishes: ["Silver", "Black", "Gold"],
      power: "4 x 1.5V AA alkaline batteries",
      battery_location: "Inside of the rear body",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storage_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate:
        "Complies with Radio Equipment Directive (RED) 2014/53/EU and RoHS standards",
    },
  },

  {
    id: "9",
    name: "F9 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F9/F9.jpg",
    images: ["/F9/F91.png", "/F9/F92.jpg", "/F9/F93.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "K5 Lock - A sleek aluminum alloy electronic lock with compact 290x62mm dimensions. Compatible with both Euro and ANSI mortise systems, it features convenient front-body battery placement for 4 AA alkaline batteries. Includes mechanical emergency override functionality and withstands extreme temperatures from -40°C to 80°C. Available in sophisticated black and coffee gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "290mm x 62mm",
      mortise_compatibility: ["Euro Mortise", "ANSI Mortise"],
      metal_finishes: ["Black", "Coffee Gold"],
      power: "4 x 1.5V Alkaline Batteries",
      battery_location: "Inside of the front body",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storable_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "10",
    name: "F6 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F6/F6.jpg",
    images: ["/F6/F61.jpg", "/F6/F62.png", "/F6/F63.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "F6 Lock - A compact aluminum alloy electronic lock with front (161x69mm) and rear (156x69mm) panels. Designed for Single Latch and 5050 mortise systems, it operates on 4 AA batteries stored in the rear body. Features mechanical emergency override and reliable performance across extreme temperatures from -40°C to 80°C. Available in satin nickel and black finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions_front: "161mm x 69mm",
      product_dimensions_rear: "156mm x 69mm",
      mortise_compatibility: ["Single Latch", "5050 Mortise"],
      color: ["Satin Nickel", "Black"],
      power: "4 x 1.5V AA alkaline batteries",
      battery_location: "Inside of the rear body",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storable_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "11",
    name: "P5 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/P5/P5.jpg",
    images: ["/P5/P51.jpg", "/P5/P52jpg", "/P5/P53.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "P5 Lock - A durable 304 stainless steel electronic lock with asymmetrical design (front: 240x78mm, rear: 303.5x78mm). Compatible with Euro and ANSI mortise systems, it runs on 4 AA batteries and features mechanical emergency override. Certified to EN14846 and EN1634 security standards, it operates reliably in extreme temperatures from -40°C to 80°C. Available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions_front: "240mm x 78mm",
      product_dimensions_rear: "303.5mm x 78mm",
      applicable_lock_body: ["Euro Mortise", "ANSI Mortise"],
      color: ["Silver", "Black", "Gold"],
      power: "4 x 1.5V AA alkaline batteries",
      battery_location: "Inside of the rear body",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storage_temperature: "-40°C to 80°C, Non-condensing Environment",
      operating_test_environment_temperature: "-20°C to 66°C",
      certificate: "Certified to EN14846:2008 and EN1634-1:2014/A:2018",
    },
  },

  {
    id: "12",
    name: "P4 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/P4/P4.jpg",
    images: ["/P4/P41.png", "/P4/P42.png", "/P4/P43.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "P4 Lock - A symmetrical aluminum alloy electronic lock with streamlined 308x76mm design. Compatible with Euro and ANSI mortise systems, it operates on 4 AA batteries and features mechanical key emergency access. Built to withstand extreme temperatures from -40°C to 80°C, ensuring reliable performance in various environments. Available in elegant black and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "308mm x 76mm",
      mortise_compatibility: ["Euro Mortise", "ANSI Mortise"],
      metal_finishes: ["Black", "Gold"],
      power: "4 x 1.5V Alkaline Batteries",
      battery_location: "Inside of the rear body",
      emergency_opening_method:
        "Emergency Unlocking with Mechanical Key Available",
      storage_temperature: "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "13",
    name: "F2 Hotel Lock",
    category: "Hotel Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F2/F2.jpg",
    images: ["/F2/F21.jpg", "/F2/F22.png", "/F2/F23.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "F2 Lock - An ultra-slim 304 stainless steel electronic lock with compact 300x38mm profile. Features extensive mortise compatibility including Euro, ANSI, and five additional types (2885/3585/4585/5572/6085). Powered by 4 AA batteries with mechanical emergency override. Triple-certified to EN14846, EN1634, and RED standards, it delivers reliable performance across extreme temperatures from -40°C to 80°C. Available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions: "300mm x 38mm",
      applicable_lock_body: [
        "Euro Mortise",
        "ANSI Mortise",
        "2885",
        "3585",
        "4585",
        "5572",
        "6085",
      ],
      color: ["Silver", "Black", "Gold"],
      battery: "4 x 1.5V Alkaline Batteries",
      battery_location: "Inside of the rear lock",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storable_environmental_temperature:
        "-40°C to 80°C, Non-condensing Environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate: ["EN14846:2008", "EN1634-1:2014/A:2018", "RED 2014/53/EU"],
    },
  },

  {
    id: "14",
    name: "KB Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/KB/KB.jpg",
    images: ["/KB/KB1.png", "/KB/KB2.jpg", "/KB/KB3.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "KB Digital Lock - A versatile aluminum alloy digital lock with a compact design (124.6×69.6×45mm). Offers multiple unlock methods including mechanical key, RFID card, PIN code, mobile phone key, and optional fingerprint recognition. Features dual power supply with 4 AAA batteries and Type-C backup, IP54 weather resistance, and reliable operation from -40°C to 80°C. RED certified and available in sleek black finish.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "124.6mm x 69.6mm x 45mm",
      metal_finishes: "Black",
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key",
        "Fingerprint (Optional)",
      ],
      power: "4 x 1.5V AAA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate:
        "Complies with the Radio Equipment Directive (RED) 2014/53/EU",
    },
  },

  {
    id: "15",
    name: "K7 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/K7/K7.jpg",
    images: ["/K7/K71.png", "/K7/K72.jpg", "/K7/K73.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "K7 Digital Lock - A versatile aluminum alloy digital lock with symmetrical 263.6×68.6mm design. Compatible with 5050, 5572, and 6085 mortise systems, it offers multiple unlock options including mechanical key, RFID card, PIN code, mobile phone key, and optional fingerprint recognition. Features dual power supply with 4 AA batteries and Type-C backup, IP54 weather resistance, and reliable performance across extreme temperatures from -40°C to 80°C. Available in black and silver finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "263.6mm x 68.6mm",
      applicable_lock_body: ["5050", "5572", "6085 Mortise"],
      metal_finishes: ["Black", "Silver"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key",
        "Fingerprint (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "16",
    name: "K8 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/K8D/K8.png",
    images: ["/K8D/K81.jpg", "/K8D/K82.jpg", "/K8D/K83.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "K8 Digital Lock - A robust aluminum alloy digital lock with asymmetrical design (front: 318×78mm, rear: 318×81.5mm). Specifically designed for 6068 mortise systems, it offers comprehensive unlock methods including mechanical key, RFID card, PIN code, and optional mobile phone key and fingerprint recognition. Features dual power supply with 4 AA batteries and Type-C backup, IP54 weather resistance, and reliable operation in extreme temperatures from -40°C to 80°C. Available in sophisticated black and coffee gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions_front: "318mm x 78mm",
      product_dimensions_rear: "318mm x 81.5mm",
      applicable_lock_body: "6068 Mortise",
      metal_finishes: ["Black", "Coffee Gold"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key (Optional)",
        "Fingerprint (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "17",
    name: "K3 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/K3/K3.jpg",
    images: ["/K3/K31.png", "/K3/K32.jpg", "/K3/K33.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "K3 Digital Lock - A sleek aluminum alloy digital lock with symmetrical 283.4×69.4mm design. Compatible with 5050, 5572, and 6085 mortise systems, it offers multiple access options including mechanical key, RFID card, PIN code, and optional fingerprint and mobile phone key recognition. Features dual power supply with 4 AA batteries and Type-C backup, IP54 weather resistance, and reliable performance in extreme temperatures from -40°C to 80°C. Available in modern black and white finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "283.4mm x 69.4mm",
      applicable_lock_body: ["5050", "5572", "6085 Mortise"],
      metal_finishes: ["Black", "White"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Fingerprint (Optional)",
        "Mobile Phone Key (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "18",
    name: "K2 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/K2D/K2.jpg",
    images: ["/K2D/K21.png", "/K2D/K22.jpg", "/K2D/K23.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "K2 Digital Lock - A versatile aluminum alloy digital lock with symmetrical 283.4×69.4mm design. Compatible with 5050, 5572, and 6085 mortise systems, it offers extensive access options including mechanical key, RFID card, PIN code, and optional fingerprint, mobile phone key, and door viewer. Features dual power supply with 4 AA batteries and Type-C backup, IP54 weather resistance, and reliable performance in extreme temperatures from -40°C to 80°C. Available in modern black and white finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "283.4mm x 69.4mm",
      applicable_lock_body: ["5050", "5572", "6085 Mortise"],
      metal_finishes: ["Black", "White"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Fingerprint (Optional)",
        "Mobile Phone Key (Optional)",
        "Door viewer (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "19",
    name: "H2 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/H2D/H2.jpg",
    images: ["/H2D/H21.png", "/H2D/H22.jpg", "/H2D/H23.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "H2 Digital Lock - A premium 304 stainless steel digital lock with an ultra-slim 303.4×41.4mm profile. Features extensive compatibility with five mortise types (2885/3585/4585/5572/6085) and multiple unlock methods including mechanical key, RFID card, PIN code, mobile phone key, and optional fingerprint recognition. Equipped with dual power supply (4 AA batteries + Type-C backup), IP54 weather resistance, and reliable operation in extreme temperatures from -40°C to 80°C. Certified to RED and RoHS standards, available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions: "303.4mm x 41.4mm",
      applicable_lock_body: ["2885", "3585", "4585", "5572", "6085 Mortise"],
      metal_finishes: ["Silver", "Black", "Gold"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key",
        "Fingerprint (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate:
        "Complies with the Radio Equipment Directive (RED) 2014/53/EU and RoHS standards",
    },
  },

  {
    id: "20",
    name: "H1 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/H1D/H1.jpg",
    images: ["/H1D/H11.png", "/H1D/H12.png", "/H1D/H13.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "H1 Digital Lock - A premium 304 stainless steel digital lock with an ultra-slim symmetrical design (303.4×41.4mm). Offers extensive mortise compatibility (2885/3585/4585/5572/6085) and multiple unlock methods including mechanical key, RFID card, PIN code, mobile phone key, and optional fingerprint recognition. Features dual power supply with 4 AA batteries and Type-C backup, IP54 weather resistance, and reliable operation in extreme temperatures from -40°C to 80°C. RED and RoHS certified, available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions: "303.4mm x 41.4mm",
      applicable_lock_body: ["2885", "3585", "4585", "5572", "6085 Mortise"],
      metal_finishes: ["Silver", "Black", "Gold"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key",
        "Fingerprint (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate:
        "Complies with the Radio Equipment Directive (RED) 2014/53/EU and RoHS standards",
    },
  },

  {
    id: "21",
    name: "F9 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F9D/F9.jpg",
    images: ["/F9D/F91.png", "/F9D/F92.jpg", "/F9D/F93.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "F9 Digital Lock - A sleek aluminum alloy digital lock with symmetrical 290×62mm design. Compatible with both Euro and ANSI mortise systems, it offers multiple access methods including mechanical key, RFID card, PIN code, and optional mobile phone key. Features dual power supply with 4 AA batteries and Type-C backup for uninterrupted operation. Built to withstand extreme temperatures from -40°C to 80°C, ensuring reliable performance in various environments. Available in sophisticated black and coffee gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "290mm x 62mm",
      applicable_lock_body: ["Euro Mortise", "ANSI Mortise"],
      metal_finishes: ["Black", "Coffee Gold"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "22",
    name: "F7 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F7D/F7.jpg",
    images: ["/F7D/F71.png", "/F7D/F72.jpg", "/F7D/F73.png"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription: "",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions_front: "285.7mm x 78mm",
      product_dimensions_rear: "303.5mm x 78mm",
      applicable_lock_body: ["Euro Mortise", "ANSI Mortise"],
      metal_finishes: ["Silver", "Black", "Gold"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key (Optional)",
        "Fingerprint (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      battery_location: "Inside of the rear body",
      emergency_opening_method:
        "Euro profile emergency opening by mechanical override",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate: "Certified to EN14846:2008 and EN1634-1:2014/A:2018",
    },
  },

  {
    id: "23",
    name: "F6 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F6D/F6.jpg",
    images: ["/F6D/F61.jpg", "/F6D/F62.png", "/F6D/F63.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "F6 Digital Lock - A compact aluminum alloy digital lock with asymmetrical design (front: 161×69mm, rear: 156×69mm). Compatible with Single Latch and 5050 mortise systems, it offers multiple access methods including mechanical key, RFID card, PIN code, and optional fingerprint and mobile phone key recognition. Features dual power supply with 4 AA batteries and Type-C backup, IP54 weather resistance, and reliable performance in extreme temperatures from -40°C to 80°C. Available in satin nickel and black finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions_front: "161mm x 69mm",
      product_dimensions_rear: "156mm x 69mm",
      applicable_lock_body: ["Single Latch", "5050 Mortise"],
      metal_finishes: ["Satin Nickel", "Black"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Fingerprint (Optional)",
        "Mobile Phone Key (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "24",
    name: "F2 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/F2D/F2.jpg",
    images: ["/F2D/F21.png", "/F2D/F22.jpg", "/F2D/F23.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "F2 Digital Lock - An ultra-slim 304 stainless steel digital lock with symmetrical 300×38mm profile. Offers exceptional mortise compatibility with nine different types (2885/3585/4085/4585/5085/5572/5585/6085/7085). Provides multiple unlock methods including mechanical key, RFID card, PIN code, mobile phone key, and optional fingerprint recognition. Features dual power supply with 4 AA batteries and Micro USB backup, IP54 weather resistance, and reliable operation in extreme temperatures from -40°C to 80°C. Available in silver, black, and gold finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "304 Stainless Steel",
      product_dimensions: "300mm x 38mm",
      applicable_lock_body: [
        "2885",
        "3585",
        "4085",
        "4585",
        "5085",
        "5572",
        "5585",
        "6085",
        "7085 Mortise",
      ],
      metal_finishes: ["Silver", "Black", "Gold"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key",
        "Fingerprint (Optional)",
      ],
      power: "4 x 1.5V AA alkaline batteries and Micro USB power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "25",
    name: "DK2 Digital Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/DK2/DK2.jpg",
    images: ["/DK2/DK21.jpg", "/DK2/DK22.jpg", "/DK2/DK23.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription:
      "K2 Digital Lock - An ultra-compact aluminum alloy digital lock measuring 145×44×32.8mm, designed for doors 60-120mm thick. Offers multiple access methods including mechanical key, RFID card, PIN code, mobile phone key, and optional fingerprint recognition. Features efficient power supply with 2 CR2 lithium batteries and Type-C backup, IP54 weather resistance, and reliable performance in extreme temperatures from -40°C to 80°C. Available in sleek black finish.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions: "145mm x 44mm x 32.8mm",
      applicable_door_thickness: "60mm - 120mm",
      metal_finishes: "Black",
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Pin Code",
        "Mobile Phone Key",
        "Fingerprint (Optional)",
      ],
      power: "2 x 3V CR2 lithium batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
    },
  },

  {
    id: "26",
    name: "Electronic Cylinder Lock",
    category: "Digital Lock",
    subcategory: "",
    description: "",
    features: [
      "Fingerprint Recognition",
      "Mobile App Control",
      "Auto-locking Function",
    ],
    imageUrl: "/EC/EC.png",
    images: ["/EC/EC1.jpg", "/EC/EC2.jpg", "/EC/EC3.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription: "Electronic Cylinder Lock - An ultra-compact aluminum alloy digital lock with miniature front (60×45×38mm) and rear (30×19×31mm) components. Compatible with both Euro (60-120mm) and ANSI (32.5-62.5mm mortise) standards. Offers multiple access methods including mechanical key, RFID card, mobile phone key, and optional fingerprint and key code recognition. Features efficient power supply with 3 AAA batteries and Type-C backup, IP54 weather resistance, and reliable operation in extreme temperatures from -40°C to 80°C. RED certified and available in silver and black finishes.",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
      material: "Aluminum Alloy",
      product_dimensions_front: "60mm x 45mm x 38mm",
      product_dimensions_rear: "30mm x 19mm x 31mm",
      euro_standard: "60mm - 120mm",
      ansi_standard:
        "Mortise length: 32.5mm (1-2/7 inches) to 62.5mm (2-4/9 inches)",
      metal_finishes: ["Silver", "Black"],
      unlock_methods: [
        "Mechanical Key",
        "RFID Card",
        "Mobile Phone Key",
        "Fingerprint (Optional)",
        "Key Code (Optional)",
      ],
      power: "3 x 1.5V AAA alkaline batteries and Type-C power back-up",
      ip_rating: "IP54",
      storage_temperature: "-40°C to 80°C, non-condensing environment",
      tested_operating_temperature: "-20°C to 66°C",
      certificate:
        "Complies with the Radio Equipment Directive (RED) 2014/53/EU",
    },
  },

  {
    id: "27",
    name: "Energy Saver",
    category: "Hotel Accessories",
    subcategory: "",
    description: "",
    features: [

    ],
    imageUrl: "/ES/ES.png",
    images: ["/ES/ES1.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription: "",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications:{
  "material": "ABS",
  "product_dimensions": "85.5mm x 85.5mm x 15mm",
  "metal_finishes": ["White", "Black"],
  "function": ["RFID Identified", "Room Number Specified", "Time Specified", "Room Number and Time Specified"],
  "voltage": "110-220VAC ±10%",
  "output_relay": "Max 16A"
},
  },

   {
    id: "28",
    name: "Handheld",
    category: "Hotel Accessories",
    subcategory: "",
    description: "",
    features: [

    ],
    imageUrl: "/HH/HH.jpg",
    images: ["/HH/HH.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription: "",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
    },
  },
  
   {
    id: "29",
    name: "Access Control",
    category: "Hotel Accessories",
    subcategory: "",
    description: "",
    features: [

    ],
    imageUrl: "/AC/AC.jpg",
    images: ["/AC/AC.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription: "",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
    },
  },
  
   {
    id: "30",
    name: "Elevator Control",
    category: "Hotel Accessories",
    subcategory: "",
    description: "",
    features: [

    ],
    imageUrl: "/ECA/EC.jpg",
    images: ["/ECA/EC.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription: "",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
    },
  },
  
  {
    id: "30",
    name: "Encoder",
    category: "Hotel Accessories",
    subcategory: "",
    description: "",
    features: [

    ],
    imageUrl: "/EN/EN.jpg",
    images: ["/EN/EN1.jpg"],
    isNew: true,
    isHot: false,
    system: "single",
    tags: ["New Product", "Single system"],
    detailedDescription: "",
    installation:
      "Easy DIY installation with included mounting hardware and detailed instructions.",
    warranty: "2 years manufacturer warranty",
    specifications: {
    },
  },
];
