// constants.js

export const sampleProducts = [
  // {
  //   id: "1",
  //   name: "V91C",
  //   category: "Push and pull Lock",
  //   subcategory: "",
  //   description: "BODINI Single system fully automatic smart lock",
  //   features: [
  //     "Fingerprint Recognition",
  //     "Mobile App Control",
  //     "Auto-locking Function",
  //   ],
  //   imageUrl: "/v26c.jpg",
  //   images: ["/v26c.jpg", "/v81c.jpg", "/c90.jpg"],
  //   isNew: true,
  //   isHot: false,
  //   system: "single",
  //   tags: ["New Product", "Single system"],
  //   detailedDescription:
  //     "The V91C is a premium single system smart lock featuring advanced fingerprint recognition technology. Built with durable zinc alloy construction, it offers secure and convenient access control for modern homes and offices.",
  //   installation:
  //     "Easy DIY installation with included mounting hardware and detailed instructions.",
  //   warranty: "2 years manufacturer warranty",
  // },
  {
    id: "2",
    name: "i9902 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Double system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i9902.jpg",
    images: ["/i99021.jpg", "/i99022.jpg", "/i99023.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "3",
    name: "i9901 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Double system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i9901.jpg",
    images: ["/i99011.jpg", "/i99012.jpg", "/i99013.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "4",
    name: "i9908 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Double system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i9908.jpg",
    images: ["/i99081.jpg", "/i99082.jpg", "/i99083.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      color: ["Black", "Red Copper"],
      battery: "4200mAh + 2250mAh Lithium Battery",
      power_supply: "6.8-8.4V",
      camera: "2 Million Pixel Independent Lens, 150° ultra wide camera",
      display: "5-Inch HD Display",
      facial_recognition: "3D Facial Recognition",
      lock_cylinder: "Solid Brass Lock Cylinder with Metal Key Handle",
      handle: "Bearing Handle for Smooth and stable Operation",
      compatibility: "Compatible with Electronic mortise",
      language: "Multi Language version",
    },
  },
  {
    id: "5",
    name: "i9909 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Double system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i9909.jpg",
    images: ["/i99091.jpg", "/i99092.jpg", "/i99093.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "6",
    name: "i995 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Double system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i995.jpg",
    images: ["/i9951.jpg", "/i9952.jpg", "/i9953.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "7",
    name: "V81C",
    category: "Push and pull Lock",
    subcategory: "",
    description: "BODINI Single system fully automatic smart lock",
    features: ["Palm Recognition", "App Notifications", "Energy Efficient"],
    imageUrl: "/v81c.jpg",
    isNew: true,
    isHot: true,
    system: "single",
    tags: ["New Product", "Hot", "Single system"],
  },
  {
    id: "8",
    name:  "A2 Waterproof Tuya wifi/ Tuya zigbee /TTlock ble APP Broken Bridge Aluminium Smart Lock",
    category: "Commercial digital locks",
    subcategory: "Slim door/window lock",
    description:
'',
    features: [
      "Slim Design (8mm)",
      "Fingerprint Recognition",
      "Bluetooth Connectivity",
      "Glass Door Compatible",
    ],
    imageUrl: "/A2.jpg",
    images: [
      "/A22.jpg",
      "/A23.jpg",
      "/A24.jpg",
      "/A25.jpg",
      "/A26.jpg",
      "/A27.jpg",
    ],
    isNew: true,
    isHot: false,
    system: "slim",
    tags: ["New Product", "Slim Design"],
    specifications: {
      Product_name: "Broken bridge aluminum fingerprint lock",
      Product_material: "Zinc alloy",
      recognition_speed: "<0.1S",
      working_power_supply: "4/8 No.7 batteries",
      work_environment: "-30C~60C",
      induction_time: "<0.5S",
      number_of_keys: "2 pieces",
      fingerprint: "100 pieces",
      password: "150 sets",
      card: "200 sheets",
      applicable_door_thickness: "30-120mm",
      applicable_types: "Indoor and outdoor",
      unlocking_method: [
        "Fingerprint",
        "Password",
        "IC Card",
        "NFC",
        "Mobile App",
        "Temporary Password",
        "Mechanical Key",
        "WiFi Remote Unlock (requires gateway)",
        "Remote Unlock (optional)",
      ],
    },
    detailedDescription:
      "The A2 ultra-slim smart lock features an innovative 8mm profile design perfect for glass doors and windows. Built with waterproof broken bridge aluminium construction and advanced Tuya connectivity options.",
    installation:
      "Specialized installation for glass doors with included mounting kit.",
    warranty: "2 years manufacturer warranty",
  },
  {
    id: "9",
    name: "A3 Smart tuya wifi /TTLock Ble app face recognition aluminum door lock",
    category: "Commercial digital locks",
    subcategory: "Slim door/window lock",
    description:
      "",
    features: [
      "Ultra-thin Profile",
      "NFC Access",
      "Auto-lock Function",
      "Weather Resistant",
    ],
    imageUrl: "/A3.png",
    images: ["/A32.png", "/A33.png", "/A34.png", "/A35.png"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium", "Slim Design"],
    specifications: {
      unlocking_ways: [
        "Face ID",
        "Fingerprint",
        "Password",
        "Card",
        "Key",
        "App",
      ],
      door_thickness: "30-65mm",
      material_body: "CNC",
      material_panel: "Tempered glass",
      capacity_fingerprint: "100 pcs",
      capacity_password: "100 pcs",
      fingerprint_sensor: "Biometrics 160*160 Pixel",
      battery: "3200maH lithium battery",
      work_voltage: "7.4V",
      default_mortise: "3585 mm swing type",
      weight: "3.5 KG",
      ip_rating: "IP65",
      app_tuya: "Tuya wifi/TTlock ble With Camera",
      app_ttlock: "TTlock version have no Camera",
    },
  },
  {
    id: "10",
    name: "DQ Waterproof TTLock Ble APP Smart Fingerprint Broken Bridge Aluminium Sliding Door Lock",
    category: "Commercial digital locks",
    subcategory: "Slim door/window lock",
    description:
      "",
    features: [
      "Compact Size",
      "PIN Code Entry",
      "Emergency Key Override",
      "Easy Installation",
    ],
    imageUrl: "/DQ.jpg",
    images: ["/DQ2.jpg", "/DQ3.jpg", "/DQ4.jpg", "/DQ5.jpg", "/DQ6.jpg"],
    isNew: false,
    isHot: false,
    system: "slim",
    tags: ["Compact", "Residential"],
  },
  {
    id: "11",
    name: "J03 Ultra-narrow Smart tuya wifi APP 3D face recognition lock",
    category: "Commercial digital locks",
    subcategory: "Slim door/window lock",
    description:
      "",
    features: [
      "Ultra-thin Profile",
      "NFC Access",
      "Auto-lock Function",
      "Weather Resistant",
    ],
    imageUrl: "/JO3.jpg",
    images: ["/JO31.jpg", "/JO32.jpg", "/JO33.jpg", "/JO34.jpg", "/JO35.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium", "Slim Design"],
  },
  {
    id: "12",
    name: "T6C Waterproof Tuya wifi APP smart face recognition door lock with camera",
    category: "Commercial digital locks",
    subcategory: "Slim door/window lock",
    description:
      "",
    features: [
      "Ultra-thin Profile",
      "NFC Access",
      "Auto-lock Function",
      "Weather Resistant",
    ],
    imageUrl: "/TC6.jpg",
    images: ["/TC61.jpg", "/TC62.jpg", "/TC63.jpg", "/TC64.jpg", "/TC65.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium", "Slim Design"],
  },
  {
    id: "13",
    name: "TP007 Smart Tuya wifi APP aluminum sliding fingerprint door lock",
    category: "Commercial digital locks",
    subcategory: "Slim door/window lock",
    description:
      "",
    features: [
      "Ultra-thin Profile",
      "NFC Access",
      "Auto-lock Function",
      "Weather Resistant",
    ],
    imageUrl: "/TP007.jpg",
    images: [
      "/TP0071.jpg",
      "/TP0072.jpg",
      "/TP0073.jpg",
      "/TP0074.jpg",
      "/TP0075.jpg",
    ],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium", "Slim Design"],
  },
  {
    id: "14",
    name: "Y02 Waterproof Tuya wifi/ Tuya zigbee /TTlock ble APP Broken Bridge Aluminium Smart Lock",
    category: "Commercial digital locks",
    subcategory: "Slim door/window lock",
    description:
      "",
    features: [
      "Ultra-thin Profile",
      "NFC Access",
      "Auto-lock Function",
      "Weather Resistant",
    ],
    imageUrl: "/YO2.jpg",
    images: ["/Y021.jpg", "/Y022.jpg", "/Y023.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium", "Slim Design"],
  },
  {
    id: "15",
    name: "K7 Tuya wifi /TTlock ble APP Smart Handle door Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/K7.jpg",
    images: ["/K71.jpg", "/K72.jpg", "/K73.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "16",
    name: "L1 Tuya wifi /Tuay Zigbee/TTlock ble APP Smart Handle Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/L1.jpg",
    images: ["/L11.jpg", "/L12.jpg", "/L13.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "17",
    name: "L2 Tuya Wifi/ TTlcok Ble/Tuya Zigbee APP Smart Fingerprint Handle Door Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description:
      "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/L2.jpg",
    images: ["/L21.jpg", "/L22.jpg", "/L23.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "18",
    name: "S10——Smart Wooden Door Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/S10.jpg",
    images: ["/S101.jpg", "/S102.jpg", "/S103.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "19",
    name: "TN9 TTLock Ble APP Smart Handles Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TN9.jpg",
    images: ["/TN91.jpg", "/TN92.jpg", "/TN93.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "20",
    name: "TX2 Tuya wifi /Tuay Zigbee/TTlock ble APP Smart Handle Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TX2.jpg",
    images: ["/TX21.jpg", "/TX22.jpg", "/TX23.jpg", "/TX24.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "21",
    name: "X1 Tuya wifi /Tuay Zigbee/TTlock ble APP Smart Handle Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/X1.jpg",
    images: ["/X11.png", "/X12.pg", "/X13.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "22",
    name: "X5 Tuya/TTlock APP ——Fingerprint Wooden Door Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/X5.jpg",
    images: ["/X51.jpg", "/X52.jpg", "/X53.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "23",
    name: "X6 Tuya Wifi /TTlcok Ble APP Smart Handle Fingerprint Door Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description:
      "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/X6.jpg",
    images: ["/X61.png", "/X62.jpg", "/X63.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "24",
    name: "X7 Tuya/TTLock APP——Fingerprint Wooden Door Smart Lock",
    category: "Commercial digital locks",
    subcategory: "Interior door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/X7.jpg",
    images: ["/X71.jpg", "/X72.jpg", "/X73.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "25",
    name: "S1F",
    category: "Commercial digital locks",
    subcategory: "Cylinder lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/S1F.jpg",
    images: ["/S1F1.jpg", "/S1F2.jpg", "/S1F3.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "26",
    name: "S1K Smart TTlock Tuya App Passcode Cylinder Door Lock",
    category: "Commercial digital locks",
    subcategory: "Cylinder lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/S1K.jpg",
    images: ["/S1K1.jpg", "/S1K2.jpg", "/S1K3.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlocking_ways: ["Password", "Key", "Card", "App"],
      door_thickness: "Default length 60mm",
      material: "Aluminum alloy",
      capacity_card: "100",
      capacity_password: "100pcs",
      fingerprint_sensor: "Biometrics 160*160Pixel",
      battery: "CR123A",
      work_voltage: "3V",
      weight: "1.1 KG",
    },
  },
  {
    id: "27",
    name: "TP11 Tuya BLE/ TTlcok Ble APP Smart Cylinder Door Lock",
    category: "Commercial digital locks",
    subcategory: "Cylinder lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TP11.png",
    images: ["/TP111.jpg", "/TP112.jpg", "/TP113.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlocking_ways: ["Fingerprint", "Password", "Key", "Card", "App"],
      door_thickness: "60-105mm",
      material: "Aluminum alloy",
      capacity_fingerprint: "100pcs",
      capacity_card: "100pcs",
      fingerprint_sensor: "Biometrics 160*160Pixel",
      battery: "4 pcs AAA alkaline batteries",
      work_voltage: "6V",
      weight: "1 KG",
    },
  },
  {
    id: "28",
    name: "906 Tuya TTLock Smart Deadbolt Ble Fingerprint Door Lock",
    category: "Commercial digital locks",
    subcategory: "Deadbolt lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/906.png",
    images: ["/9061.png", "/9062.png", "/9063.png"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "29",
    name: "A1 Tuya wifi / TTlock ble APP Smart Deadbolt Fingerprint Door Lock",
    category: "Commercial digital locks",
    subcategory: "Deadbolt lock",
    description:
      "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/A1.jpg",
    images: ["/A11.jpg", "/A12.jpg", "/A13.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "30",
    name: "S6D Tuya wifi Smart Deadbolt Door Lock",
    category: "Commercial digital locks",
    subcategory: "Deadbolt lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TP11.jpg",
    images: ["/S6D1.jpg", "/S6D2.jpg", "/S6D3.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "31",
    name: "XN1 Tuya wifi / TTlock ble APP Smart Deadbolt Door Lock in Deadbolt lock",
    category: "Commercial digital locks",
    subcategory: "Deadbolt lock",
    description:
      "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/XN1.jpg",
    images: ["/XN11.png", "/XN12.png", "/XN13.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "32",
    name: "K10 Pro Tuya ble Smart Fingerprint Password Knob Lock",
    category: "Commercial digital locks",
    subcategory: "Knob Lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/K10.jpg",
    images: ["/K101.jpg", "/K102.jpg", "/K103.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "33",
    name: "K10 Tuya ble APP smart knob fingerprint lock",
    category: "Commercial digital locks",
    subcategory: "Knob Lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/K1011.jpg",
    images: ["/K1011.jpg", "/K1012.jpg", "/K1013.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "34",
    name: "TP16 Tuya Ble/ TTlock Ble APP Smart knob fingerprint lock",
    category: "Commercial digital locks",
    subcategory: "Knob Lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TP16.jpg",
    images: ["/TP161.jpg", "/TP162.jpg", "/TP163.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "35",
    name: "B3 Tuya Fingerprint Lever Lock",
    category: "Commercial digital locks",
    subcategory: "Lever handle lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/B3.jpg",
    images: ["/B31.jpg", "/B32.jpg", "/B33.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlock_way: [
        "APP",
        "Fingerprint",
        "IC Card",
        "Mechanical key",
        "Password",
      ],
      product_app: ["TTLock (Ble)", "Tuya (Wifi)"],
      battery: "4 Pcs AAA alkaline batteries",
      material: "Aluminum alloy",
      product_color: ["Black", "Silver"],
      door_thickness: "35-55 mm",
      emergency_access: "Type-c port",
      working_environment: "-25℃~60℃, 20%~90%RH",
      default_mortise: "Adjustable 60/70mm Single Latch",
    },
  },
  {
    id: "36",
    name: "H3 TTLock Ble /Wifi APP Smart biometric fingerprint door lever lock",
    category: "Commercial digital locks",
    subcategory: "Lever handle lock",
    description:
      "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/H3.jpg",
    images: ["/H31.jpg", "/H32.jpg", "/H33.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "37",
    name: "O3 Smart Fingerprint Tuya Wifi Ttlock App Lever Handle Door Lock",
    category: "Commercial digital locks",
    subcategory: "Lever handle lock",
    description:
      "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/O3.jpg",
    images: ["/O31.jpg", "/O32.png", "/O33.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "38",
    name: "S6-Pro Tuya Ble /TTlock Ble App Smart Lever Door Lock",
    category: "Commercial digital locks",
    subcategory: "Lever handle lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/S6.jpg",
    images: ["/S61.jpg", "/S62.jpg", "/S63.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "39",
    name: "T4 Tuya Ble / TTlock Ble Smart Fingerprint Wooden Lever Door Lock",
    category: "Commercial digital locks",
    subcategory: "Lever handle lock",
    description:
      "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/T4.jpg",
    images: ["/T41.jpg", "/T42.jpg", "/T43.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "40",
    name: "TH24 Tuya Ble /TTlock Ble App Smart Lever Door Lock",
    category: "Commercial digital locks",
    subcategory: "Lever handle lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TH24.jpg",
    images: ["/TH241.jpg", "/TH242.png", "/TH243.png"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "41",
    name: "D1 Tuya wifi / TTlock ble APP Smart Rim Lock",
    category: "Commercial digital locks",
    subcategory: "Rim lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/D1.jpg",
    images: ["/D11.jpg", "/D12.jpg", "/D13.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "42",
    name: "D2 Waterproof Tuya wifi/TTlock ble APP smart double side rim lock",
    category: "Commercial digital locks",
    subcategory: "Rim lock",
    description:
      "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/D2.jpg",
    images: ["/D21.jpg", "/D22.jpg", "/D23.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "43",
    name: "D3 Tuya wifi/TTlock ble APP RIM smart lock",
    category: "Commercial digital locks",
    subcategory: "Rim lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/D3.jpg",
    images: ["/D31.jpg", "/D32.jpg", "/D33.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "44",
    name: "G7 Tuya wifi App Smart Biometric Fingerprint Office Glass Door Lock",
    category: "Commercial digital locks",
    subcategory: "Glass door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/G7.jpg",
    images: ["/G71.jpg", "/G72.jpg", "/G73.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "45",
    name: "G9 Office Smart Tuya TTlock Glass Door Lock",
    category: "Commercial digital locks",
    subcategory: "Glass door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/G9.jpg",
    images: ["/G91.jpg", "/G92.jpg", "/G93.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "46",
    name: "TP-G5 Tuya wifi/ TTlock ble /Ttlock wifi App Smart face recognition Glass Lock For Office",
    category: "Commercial digital locks",
    subcategory: "Glass door lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TP.jpg",
    images: ["/TP1.jpg", "/TP2.jpg", "/TP3.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "47",
    name: "Q5 TTlock ble /TTlock wifi/ Tuya Wifi/ Tuya zigbee APP Smart Handle Lock",
    category: "Commercial digital locks",
    subcategory: "Apartment lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/Q5.jpg",
    images: ["/Q51.jpg", "/Q52.jpg", "/Q53.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "48",
    name: "Q6 TTlock ble /TTlock wifi/ Tuya Wifi/ Tuya zigbee APP Smart Handle Lock",
    category: "Commercial digital locks",
    subcategory: "Apartment lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/Q6.jpg",
    images: ["/Q61.jpg", "/Q62.jpg", "/Q63.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "49",
    name: "TX8 TTLock Ble APP Smart Fingerprint Handle Keyless Door Lock",
    category: "Commercial digital locks",
    subcategory: "Apartment lock",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TX8.jpg",
    images: ["/TX81.jpg", "/TX82.jpg", "/TX83.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "50",
    name: "C90 BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "New Product",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/c90.jpg",
    images: ["/C901.jpg", "/C902.jpg", "/C903.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "51",
    name: "i9901 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "New Product",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i9901.jpg",
    images: ["/i99011.jpg", "/i99012.jpg", "/i99013.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "52",
    name: "i9902 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "New Product",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i9902.jpg",
    images: ["/i99021.jpg", "/i99022.jpg", "/i99023.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "53",
    name: "i9908 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "New Product",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i9908.jpg",
    images: ["/i99081.jpg", "/i99082.jpg", "/i99083.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      color: ["Black", "Red Copper"],
      battery: "4200mAh + 2250mAh Lithium Battery",
      power_supply: "6.8-8.4V",
      camera: "2 Million Pixel Independent Lens, 150° ultra wide camera",
      display: "5-Inch HD Display",
      facial_recognition: "3D Facial Recognition",
      lock_cylinder: "Solid Brass Lock Cylinder with Metal Key Handle",
      handle: "Bearing Handle for Smooth and stable Operation",
      compatibility: "Compatible with Electronic mortise",
      language: "Multi Language version",
    },
  },
  {
    id: "54",
    name: "i9909 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "New Product",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i9909.jpg",
    images: ["/i99091.jpg", "/i99092.jpg", "/i99093.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "55",
    name: "i995 BODNI Double system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "New Product",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i995.jpg",
    images: ["/i9951.jpg", "/i9952.jpg", "/i9953.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "56",
    name: "V81C BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "New Product",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/i995.jpg",
    images: ["/i9951.jpg", "/i9952.jpg", "/i9953.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "57",
    name: "991L BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Single system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/991L.jpg",
    images: ["/991L.jpg", "/991L.jpg", "/991L.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlock_way: [
        "3D Face Recognition",
        "APP",
        "Fingerprint",
        "IC Card",
        "Mechanical key",
        "Palmar vein",
        "Password",
      ],
      battery: "5000mAh lithium battery",
      feature: ["Active Video intercom", "Multi Language version"],
      emergency_access: "Type-c port",
      product_color: "Black",
      camera: "3 Million Pixel independent Lens, 150° Ultra Wide-Angle Camera",
      display: "5-Inch HD Display",
      lock_cylinder_and_handle:
        "Solid Brass Lock Cylinder with Metal Key Handle",
      default_mortise:
        "Electronic mortise 6068 24*240mm/30*240mm, Mortise 6068 24*240mm/30*240mm",
      door_lock_status_reminder: [
        "Abnormal door opening reminder",
        "Door opening reminder message",
        "Low battery reminder",
      ],
      product_app: "ICsee Home (Wifi)",
    },
  },
  {
    id: "58",
    name: "993L BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Single system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/993L.jpg",
    images: ["/993L.jpg", "/993L.jpg", "/993L.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlock_way: [
        "3D Face Recognition",
        "APP",
        "Fingerprint",
        "IC Card",
        "Mechanical key",
        "Palmar vein",
        "Password",
      ],
      battery: "5000mAh lithium battery",
      feature: ["Active Video intercom", "Multi Language version"],
      emergency_access: "Type-c port",
      product_color: "Black",
      camera: "3 Million Pixel independent Lens, 150° Ultra Wide-Angle Camera",
      display: "5-Inch HD Display",
      lock_cylinder_and_handle:
        "Solid Brass Lock Cylinder with Metal Key Handle",
      default_mortise:
        "Electronic mortise 6068 24*240mm/30*240mm, Mortise 6068 24*240mm/30*240mm",
      door_lock_status_reminder: [
        "Abnormal door opening reminder",
        "Door opening reminder message",
        "Low battery reminder",
      ],
      product_app: "ICsee Home (Wifi)",
    },
  },
  {
    id: "59",
    name: "C90 BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Single system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/c90.jpg",
    images: ["/C901.jpg", "/C902.jpg", "/C903.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "60",
    name: "M20 BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Single system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/M20.jpg",
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlock_way: [
        "3D Face Recognition",
        "APP",
        "Fingerprint",
        "IC Card",
        "Mechanical key",
        "Palmar vein",
        "Password",
      ],
      battery: "5000mAh lithium battery",
      feature: ["Active Video intercom", "Multi Language version"],
      emergency_access: "Type-c port",
      product_color: "Black",
      camera: "3 Million Pixel independent Lens, 150° Ultra Wide-Angle Camera",
      display: "5-Inch HD Display",
      lock_cylinder_and_handle:
        "Solid Brass Lock Cylinder with Metal Key Handle",
      default_mortise:
        "Electronic mortise 6068 24*240mm/30*240mm, Mortise 6068 24*240mm/30*240mm",
      door_lock_status_reminder: [
        "Abnormal door opening reminder",
        "Door opening reminder message",
        "low battery reminder",
      ],
      product_app: "ICsee Home (Wifi)",
    },
  },
  {
    id: "61",
    name: "M50 BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Single system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/M50.jpg",
    // images: ["/M501.jpg", "/M502.jpg", "/M503.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlock_way: [
        "3D Face Recognition",
        "APP",
        "Fingerprint",
        "IC Card",
        "Mechanical key",
        "Palmar vein",
        "Password",
      ],
      battery: "5000mAh lithium battery",
      feature: ["Active Video intercom", "Multi Language version"],
      emergency_access: "Type-c port",
      product_color: "Black",
      camera: "3 Million Pixel independent Lens, 150° Ultra Wide-Angle Camera",
      display: "5-Inch HD Display",
      lock_cylinder_and_handle:
        "Solid Brass Lock Cylinder with Metal Key Handle",
      default_mortise:
        "Electronic mortise 6068 24*240mm/30*240mm, Mortise 6068 24*240mm/30*240mm",
      door_lock_status_reminder: [
        "Abnormal door opening reminder",
        "Door opening reminder message",
        "low battery reminder",
      ],
      product_app: "ICsee Home (Wifi)",
    },
  },
  {
    id: "62",
    name: "M60 BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Single system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/M60.jpg",
    // images: ["/M601.jpg", "/M602.jpg", "/M603.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlock_way: [
        "3D Face Recognition",
        "APP",
        "Fingerprint",
        "IC Card",
        "Mechanical key",
        "Palmar vein",
        "Password",
      ],
      battery: "5000mAh lithium battery",
      feature: ["Active Video intercom", "Multi Language version"],
      emergency_access: "Type-c port",
      product_color: "Black",
      camera: "3 Million Pixel independent Lens, 150° Ultra Wide-Angle Camera",
      display: "5-Inch HD Display",
      lock_cylinder_and_handle:
        "Solid Brass Lock Cylinder with Metal Key Handle",
      default_mortise:
        "Electronic mortise 6068 24*240mm/30*240mm, Mortise 6068 24*240mm/30*240mm",
      door_lock_status_reminder: [
        "Abnormal door opening reminder",
        "Door opening reminder message",
        "Low battery reminder",
      ],
      product_app: "ICsee Home (Wifi)",
    },
  },
  {
    id: "63",
    name: "V81C BODNI Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Single system",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/V8.jpg",
    images: ["/V81.jpg", "/V82.jpg", "/V83.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      product_name: "Automatic Smart Door Lock",
      unlocking_methods:
        "Palm vein, Face, Fingerprint, Password, Card, Key, App",
      door_thickness: "40-120mm",
      material: "CNC, Tempered Glass",
      capacity_fingerprint: "100",
      capacity_card: "100",
      capacity_password: "100",
      fingerprint_sensor: "Biometrics 160x160pixel",
      power_supply: "7.4V 4200mAH lithium battery",
      work_voltage: "6.8-8.4V",
      default_mortise: "6068 240x24mm",
      compatible_mortise: "Electronic mortise (+3usd)",
      weight: "5 KG",
      features: "Multi Language version, Active Video intercom",
    },
  },
  {
    id: "64",
    name: "New Product",
    category: "Push and pull lock",
    subcategory: "Models For Local Offline Brand",
    description: "",
    imageUrl: "/NP.png",
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "65",
    name: "Double system",
    category: "Push and pull lock",
    subcategory: "Models For Local Offline Brand",
    description: "",
    imageUrl: "/DS.jpg",
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "66",
    name: "Single system",
    category: "Push and pull lock",
    subcategory: "Models For Local Offline Brand",
    description: "",
    imageUrl: "/SS.png",
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "67",
    name: "ND1 Tuya wifi / zigbee APP Face Recognition Smart Lock",
    category: "Push and pull lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/ND1.png",
    images: ["/ND11.png", "/ND12.png", "/ND13.png"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "68",
    name: "TK01 Tuya wifi APP Face Recognition Smart Lock",
    category: "Push and pull lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TK01.jpg",
    images: ["/TKO11.jpg", "/TKO12.jpg", "/TKO13.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "69",
    name: "TK02 Tuya wifi APP Face Recognition Smart Lock",
    category: "Push and pull lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/TK02.jpg",
    images: ["/TK021.jpg", "/TK022.jpg", "/TK023.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "70",
    name: "US8 Tuya wifi /Usmart Go Wifi APP Face Recognition Smart Lock",
    category: "Push and pull lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/US8.jpg",
    images: ["/US81.jpg", "/US82.jpg", "/US83.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "71",
    name: "V26C Single system fully automatic smart lock",
    category: "Push and pull lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/v26c.jpg",
    images: ["/V26C1.jpg", "/V262.jpg", "/V26C.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
    specifications: {
      unlock_way:
        "3D Face Recognition, APP, Fingerprint, IC Card, Mechanical key, Palm print, Password",
      product_color: "Grey",
      product_app: "Tuya (Wifi)",
      material: "Aluminum alloy, IML frosting process",
      battery: "4200 mAh 7.4V lithium battery",
      work_voltage: "6.8-8.4V",
      emergency_access: "USB port",
      door_thickness: "40-120 mm",
      default_mortise: "6068 240*24mm",
      weight: "5kg",
    },
  },
  {
    id: "72",
    name: "X10 Tuya wifi/ Usmart Go Wifi APP Face Recognition Smart Lock",
    category: "Push and pull lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/X10.jpg",
    images: ["/X101.jpg", "/X102.png", "/X103.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "73",
    name: "X11 Tuya wifi/Usmart Go Wifi APP Face Recognition Smart Lock",
    category: "Push and pull lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/X11.jpg",
    images: ["/X111.jpg", "/X112.png", "/X113.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "74",
    name: "XD6 Pro Tuya Wifi APP –Active Video Intercom Face Recognition Support Alexa and Google home Smart Lock",
    category: "Push and pull lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/XD6.jpg",
    images: ["/XD61.jpg", "/XD62.jpg", "/XD63.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
  {
    id: "75",
    name: "Z2Pro Tuya Wifi APP –Automatic Active Video Intercom Face Palm vein Recognition Smart Lock",
    subcategory: "Models for Online RTS",
    description: "",
    features: ["NFC Access", "Auto-lock Function", "Weather Resistant"],
    imageUrl: "/Z2.jpg",
    images: ["/Z21.jpg", "/Z22.jpg", "/Z23.jpg"],
    isNew: false,
    isHot: true,
    system: "slim",
    tags: ["Hot", "Premium"],
  },
];
